// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="array_io_array_io,hls_ip_2022_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flgb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.581000,HLS_SYN_LAT=17,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1242,HLS_SYN_LUT=2199,HLS_VERSION=2022_1}" *)

module array_io (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d_o_0_din,
        d_o_0_full_n,
        d_o_0_write,
        d_o_1_din,
        d_o_1_full_n,
        d_o_1_write,
        d_i_0_address0,
        d_i_0_ce0,
        d_i_0_q0,
        d_i_0_address1,
        d_i_0_ce1,
        d_i_0_q1,
        d_i_1_address0,
        d_i_1_ce0,
        d_i_1_q0,
        d_i_1_address1,
        d_i_1_ce1,
        d_i_1_q1,
        d_i_2_address0,
        d_i_2_ce0,
        d_i_2_q0,
        d_i_2_address1,
        d_i_2_ce1,
        d_i_2_q1,
        d_i_3_address0,
        d_i_3_ce0,
        d_i_3_q0,
        d_i_3_address1,
        d_i_3_ce1,
        d_i_3_q1
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] d_o_0_din;
input   d_o_0_full_n;
output   d_o_0_write;
output  [15:0] d_o_1_din;
input   d_o_1_full_n;
output   d_o_1_write;
output  [2:0] d_i_0_address0;
output   d_i_0_ce0;
input  [15:0] d_i_0_q0;
output  [2:0] d_i_0_address1;
output   d_i_0_ce1;
input  [15:0] d_i_0_q1;
output  [2:0] d_i_1_address0;
output   d_i_1_ce0;
input  [15:0] d_i_1_q0;
output  [2:0] d_i_1_address1;
output   d_i_1_ce1;
input  [15:0] d_i_1_q1;
output  [2:0] d_i_2_address0;
output   d_i_2_ce0;
input  [15:0] d_i_2_q0;
output  [2:0] d_i_2_address1;
output   d_i_2_ce1;
input  [15:0] d_i_2_q1;
output  [2:0] d_i_3_address0;
output   d_i_3_ce0;
input  [15:0] d_i_3_q0;
output  [2:0] d_i_3_address1;
output   d_i_3_ce1;
input  [15:0] d_i_3_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] d_o_0_din;
reg d_o_0_write;
reg[15:0] d_o_1_din;
reg d_o_1_write;
reg[2:0] d_i_0_address0;
reg d_i_0_ce0;
reg[2:0] d_i_0_address1;
reg d_i_0_ce1;
reg[2:0] d_i_1_address0;
reg d_i_1_ce0;
reg[2:0] d_i_1_address1;
reg d_i_1_ce1;
reg[2:0] d_i_2_address0;
reg d_i_2_ce0;
reg[2:0] d_i_2_address1;
reg d_i_2_ce1;
reg[2:0] d_i_3_address0;
reg d_i_3_ce0;
reg[2:0] d_i_3_address1;
reg d_i_3_ce1;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] acc_0;
reg   [31:0] acc_1;
reg   [31:0] acc_2;
reg   [31:0] acc_3;
reg   [31:0] acc_4;
reg   [31:0] acc_5;
reg   [31:0] acc_6;
reg   [31:0] acc_7;
reg    d_o_0_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
reg    d_o_1_blk_n;
reg  signed [15:0] reg_402;
wire    ap_CS_fsm_state2;
reg    ap_block_state6;
reg  signed [15:0] reg_407;
reg  signed [15:0] reg_412;
reg    ap_block_state3;
reg    ap_block_state7;
reg  signed [15:0] reg_417;
reg  signed [15:0] reg_422;
reg  signed [15:0] reg_427;
reg  signed [15:0] reg_432;
reg  signed [15:0] reg_437;
reg  signed [15:0] reg_442;
reg    ap_block_state4;
reg    ap_block_state5;
reg  signed [15:0] reg_446;
reg  signed [15:0] reg_450;
reg  signed [15:0] reg_454;
wire   [15:0] add_ln69_fu_466_p2;
reg   [15:0] add_ln69_reg_1141;
wire   [15:0] add_ln69_1_fu_481_p2;
reg   [15:0] add_ln69_1_reg_1149;
wire   [15:0] add_ln69_2_fu_496_p2;
reg   [15:0] add_ln69_2_reg_1187;
wire   [15:0] add_ln69_3_fu_511_p2;
reg   [15:0] add_ln69_3_reg_1195;
reg  signed [15:0] d_i_0_load_1_reg_1200;
reg  signed [15:0] d_i_1_load_1_reg_1206;
wire   [15:0] add_ln69_4_fu_526_p2;
reg   [15:0] add_ln69_4_reg_1255;
wire   [15:0] add_ln69_5_fu_540_p2;
reg   [15:0] add_ln69_5_reg_1263;
reg  signed [15:0] d_i_2_load_1_reg_1268;
reg  signed [15:0] d_i_3_load_1_reg_1274;
wire   [15:0] add_ln69_8_fu_546_p2;
reg   [15:0] add_ln69_8_reg_1280;
wire   [15:0] add_ln69_9_fu_551_p2;
reg   [15:0] add_ln69_9_reg_1285;
wire   [15:0] add_ln69_16_fu_560_p2;
reg   [15:0] add_ln69_16_reg_1300;
wire   [15:0] add_ln69_17_fu_570_p2;
reg   [15:0] add_ln69_17_reg_1306;
reg  signed [15:0] d_i_0_load_6_reg_1322;
wire   [16:0] add_ln67_1_fu_580_p2;
reg   [16:0] add_ln67_1_reg_1327;
reg  signed [15:0] d_i_1_load_6_reg_1332;
wire   [16:0] add_ln67_5_fu_590_p2;
reg   [16:0] add_ln67_5_reg_1337;
wire   [15:0] add_ln69_6_fu_612_p2;
reg   [15:0] add_ln69_6_reg_1355;
wire   [15:0] add_ln69_7_fu_626_p2;
reg   [15:0] add_ln69_7_reg_1363;
wire   [15:0] add_ln69_10_fu_640_p2;
reg   [15:0] add_ln69_10_reg_1368;
wire   [15:0] add_ln69_11_fu_645_p2;
reg   [15:0] add_ln69_11_reg_1373;
wire   [15:0] add_ln69_18_fu_654_p2;
reg   [15:0] add_ln69_18_reg_1378;
wire   [15:0] add_ln69_19_fu_664_p2;
reg   [15:0] add_ln69_19_reg_1384;
reg  signed [15:0] d_i_2_load_6_reg_1400;
wire   [16:0] add_ln67_9_fu_734_p2;
reg   [16:0] add_ln67_9_reg_1405;
reg  signed [15:0] d_i_3_load_6_reg_1410;
wire   [16:0] add_ln67_13_fu_744_p2;
reg   [16:0] add_ln67_13_reg_1415;
wire   [16:0] add_ln67_17_fu_838_p2;
reg   [16:0] add_ln67_17_reg_1430;
wire   [16:0] add_ln67_21_fu_848_p2;
reg   [16:0] add_ln67_21_reg_1435;
wire   [15:0] add_ln69_12_fu_864_p2;
reg   [15:0] add_ln69_12_reg_1450;
wire   [15:0] add_ln69_13_fu_873_p2;
reg   [15:0] add_ln69_13_reg_1455;
wire   [15:0] add_ln69_20_fu_878_p2;
reg   [15:0] add_ln69_20_reg_1460;
wire   [15:0] add_ln69_21_fu_884_p2;
reg   [15:0] add_ln69_21_reg_1466;
wire   [16:0] add_ln67_25_fu_962_p2;
reg   [16:0] add_ln67_25_reg_1472;
wire   [16:0] add_ln67_29_fu_972_p2;
reg   [16:0] add_ln67_29_reg_1477;
wire   [15:0] add_ln69_14_fu_988_p2;
reg   [15:0] add_ln69_14_reg_1482;
wire   [15:0] add_ln69_15_fu_997_p2;
reg   [15:0] add_ln69_15_reg_1488;
wire   [15:0] add_ln69_22_fu_1062_p2;
reg   [15:0] add_ln69_22_reg_1494;
wire   [15:0] add_ln69_23_fu_1067_p2;
reg   [15:0] add_ln69_23_reg_1500;
wire   [15:0] add_ln69_24_fu_1072_p2;
reg   [15:0] add_ln69_24_reg_1506;
wire   [15:0] add_ln69_25_fu_1076_p2;
reg   [15:0] add_ln69_25_reg_1511;
wire   [15:0] add_ln69_26_fu_1080_p2;
reg   [15:0] add_ln69_26_reg_1516;
wire   [15:0] add_ln69_27_fu_1084_p2;
reg   [15:0] add_ln69_27_reg_1521;
wire   [15:0] add_ln69_28_fu_1088_p2;
reg   [15:0] add_ln69_28_reg_1526;
wire   [15:0] add_ln69_29_fu_1093_p2;
reg   [15:0] add_ln69_29_reg_1531;
wire   [15:0] add_ln69_30_fu_1098_p2;
reg   [15:0] add_ln69_30_reg_1536;
wire   [15:0] add_ln69_31_fu_1103_p2;
reg   [15:0] add_ln69_31_reg_1541;
wire   [31:0] temp_fu_688_p2;
wire   [31:0] temp_1_fu_718_p2;
wire   [31:0] temp_2_fu_792_p2;
wire   [31:0] temp_3_fu_822_p2;
wire   [31:0] temp_4_fu_916_p2;
reg    ap_block_state8;
wire   [31:0] temp_5_fu_946_p2;
wire   [31:0] temp_6_fu_1020_p2;
reg    ap_block_state9;
wire   [31:0] temp_7_fu_1050_p2;
reg    ap_block_state10;
reg    ap_block_state11;
reg    ap_block_state12;
reg    ap_block_state13;
reg    ap_block_state14;
reg    ap_block_state15;
reg    ap_block_state16;
reg    ap_block_state17;
reg    ap_block_state18;
wire   [15:0] trunc_ln67_fu_462_p1;
wire   [15:0] trunc_ln67_1_fu_477_p1;
wire   [15:0] trunc_ln67_2_fu_492_p1;
wire   [15:0] trunc_ln67_3_fu_507_p1;
wire   [15:0] trunc_ln67_4_fu_522_p1;
wire   [15:0] trunc_ln67_5_fu_536_p1;
wire  signed [15:0] sext_ln67_8_fu_576_p0;
wire  signed [16:0] sext_ln69_8_fu_556_p1;
wire  signed [16:0] sext_ln67_8_fu_576_p1;
wire  signed [15:0] sext_ln67_11_fu_586_p0;
wire  signed [16:0] sext_ln69_9_fu_566_p1;
wire  signed [16:0] sext_ln67_11_fu_586_p1;
wire   [15:0] trunc_ln67_6_fu_608_p1;
wire   [15:0] trunc_ln67_7_fu_622_p1;
wire  signed [31:0] sext_ln67_fu_596_p1;
wire  signed [17:0] sext_ln67_9_fu_675_p1;
wire  signed [17:0] sext_ln69_fu_632_p1;
wire   [17:0] add_ln67_2_fu_678_p2;
wire  signed [31:0] sext_ln67_10_fu_684_p1;
wire   [31:0] add_ln67_fu_670_p2;
wire  signed [31:0] sext_ln67_1_fu_600_p1;
wire  signed [17:0] sext_ln67_12_fu_705_p1;
wire  signed [17:0] sext_ln69_1_fu_636_p1;
wire   [17:0] add_ln67_6_fu_708_p2;
wire  signed [31:0] sext_ln67_13_fu_714_p1;
wire   [31:0] add_ln67_4_fu_700_p2;
wire  signed [15:0] sext_ln67_14_fu_730_p0;
wire  signed [16:0] sext_ln69_10_fu_650_p1;
wire  signed [16:0] sext_ln67_14_fu_730_p1;
wire  signed [15:0] sext_ln67_17_fu_740_p0;
wire  signed [16:0] sext_ln69_11_fu_660_p1;
wire  signed [16:0] sext_ln67_17_fu_740_p1;
wire  signed [31:0] sext_ln67_2_fu_750_p1;
wire  signed [17:0] sext_ln67_15_fu_779_p1;
wire  signed [17:0] sext_ln69_2_fu_758_p1;
wire   [17:0] add_ln67_10_fu_782_p2;
wire  signed [31:0] sext_ln67_16_fu_788_p1;
wire   [31:0] add_ln67_8_fu_774_p2;
wire  signed [31:0] sext_ln67_3_fu_754_p1;
wire  signed [17:0] sext_ln67_18_fu_809_p1;
wire  signed [17:0] sext_ln69_3_fu_762_p1;
wire   [17:0] add_ln67_14_fu_812_p2;
wire  signed [31:0] sext_ln67_19_fu_818_p1;
wire   [31:0] add_ln67_12_fu_804_p2;
wire  signed [15:0] sext_ln67_20_fu_834_p0;
wire  signed [16:0] sext_ln69_12_fu_766_p1;
wire  signed [16:0] sext_ln67_20_fu_834_p1;
wire  signed [15:0] sext_ln67_23_fu_844_p0;
wire  signed [16:0] sext_ln69_13_fu_770_p1;
wire  signed [16:0] sext_ln67_23_fu_844_p1;
wire  signed [31:0] sext_ln67_4_fu_854_p1;
wire  signed [17:0] sext_ln67_21_fu_903_p1;
wire  signed [17:0] sext_ln69_4_fu_860_p1;
wire   [17:0] add_ln67_18_fu_906_p2;
wire  signed [31:0] sext_ln67_22_fu_912_p1;
wire   [31:0] add_ln67_16_fu_898_p2;
wire  signed [31:0] sext_ln67_5_fu_857_p1;
wire  signed [17:0] sext_ln67_24_fu_933_p1;
wire  signed [17:0] sext_ln69_5_fu_869_p1;
wire   [17:0] add_ln67_22_fu_936_p2;
wire  signed [31:0] sext_ln67_25_fu_942_p1;
wire   [31:0] add_ln67_20_fu_928_p2;
wire  signed [15:0] sext_ln67_26_fu_958_p0;
wire  signed [16:0] sext_ln69_14_fu_890_p1;
wire  signed [16:0] sext_ln67_26_fu_958_p1;
wire  signed [15:0] sext_ln67_29_fu_968_p0;
wire  signed [16:0] sext_ln69_15_fu_894_p1;
wire  signed [16:0] sext_ln67_29_fu_968_p1;
wire  signed [31:0] sext_ln67_6_fu_978_p1;
wire  signed [17:0] sext_ln67_27_fu_1007_p1;
wire  signed [17:0] sext_ln69_6_fu_984_p1;
wire   [17:0] add_ln67_26_fu_1010_p2;
wire  signed [31:0] sext_ln67_28_fu_1016_p1;
wire   [31:0] add_ln67_24_fu_1002_p2;
wire  signed [31:0] sext_ln67_7_fu_981_p1;
wire  signed [17:0] sext_ln67_30_fu_1037_p1;
wire  signed [17:0] sext_ln69_7_fu_993_p1;
wire   [17:0] add_ln67_30_fu_1040_p2;
wire  signed [31:0] sext_ln67_31_fu_1046_p1;
wire   [31:0] add_ln67_28_fu_1032_p2;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 acc_0 = 32'd0;
#0 acc_1 = 32'd0;
#0 acc_2 = 32'd0;
#0 acc_3 = 32'd0;
#0 acc_4 = 32'd0;
#0 acc_5 = 32'd0;
#0 acc_6 = 32'd0;
#0 acc_7 = 32'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        reg_402 <= d_i_0_q1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_402 <= d_i_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        reg_407 <= d_i_1_q1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_407 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            reg_412 <= d_i_2_q1;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            reg_412 <= d_i_2_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            reg_417 <= d_i_3_q1;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            reg_417 <= d_i_3_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        reg_422 <= d_i_0_q1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        reg_422 <= d_i_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        reg_427 <= d_i_1_q1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        reg_427 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_432 <= d_i_2_q1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_432 <= d_i_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_437 <= d_i_3_q1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_437 <= d_i_3_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_0 <= temp_fu_688_p2;
        acc_1 <= temp_1_fu_718_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        acc_2 <= temp_2_fu_792_p2;
        acc_3 <= temp_3_fu_822_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
        acc_4 <= temp_4_fu_916_p2;
        acc_5 <= temp_5_fu_946_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
        acc_6 <= temp_6_fu_1020_p2;
        acc_7 <= temp_7_fu_1050_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln67_13_reg_1415 <= add_ln67_13_fu_744_p2;
        add_ln67_9_reg_1405 <= add_ln67_9_fu_734_p2;
        add_ln69_10_reg_1368 <= add_ln69_10_fu_640_p2;
        add_ln69_11_reg_1373 <= add_ln69_11_fu_645_p2;
        add_ln69_18_reg_1378 <= add_ln69_18_fu_654_p2;
        add_ln69_19_reg_1384 <= add_ln69_19_fu_664_p2;
        add_ln69_6_reg_1355 <= add_ln69_6_fu_612_p2;
        add_ln69_7_reg_1363 <= add_ln69_7_fu_626_p2;
        d_i_2_load_6_reg_1400 <= d_i_2_q1;
        d_i_3_load_6_reg_1410 <= d_i_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln67_17_reg_1430 <= add_ln67_17_fu_838_p2;
        add_ln67_21_reg_1435 <= add_ln67_21_fu_848_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln67_1_reg_1327 <= add_ln67_1_fu_580_p2;
        add_ln67_5_reg_1337 <= add_ln67_5_fu_590_p2;
        add_ln69_16_reg_1300 <= add_ln69_16_fu_560_p2;
        add_ln69_17_reg_1306 <= add_ln69_17_fu_570_p2;
        add_ln69_4_reg_1255 <= add_ln69_4_fu_526_p2;
        add_ln69_5_reg_1263 <= add_ln69_5_fu_540_p2;
        add_ln69_8_reg_1280 <= add_ln69_8_fu_546_p2;
        add_ln69_9_reg_1285 <= add_ln69_9_fu_551_p2;
        d_i_0_load_6_reg_1322 <= d_i_0_q1;
        d_i_1_load_6_reg_1332 <= d_i_1_q1;
        d_i_2_load_1_reg_1268 <= d_i_2_q1;
        d_i_3_load_1_reg_1274 <= d_i_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln67_25_reg_1472 <= add_ln67_25_fu_962_p2;
        add_ln67_29_reg_1477 <= add_ln67_29_fu_972_p2;
        add_ln69_12_reg_1450 <= add_ln69_12_fu_864_p2;
        add_ln69_13_reg_1455 <= add_ln69_13_fu_873_p2;
        add_ln69_20_reg_1460 <= add_ln69_20_fu_878_p2;
        add_ln69_21_reg_1466 <= add_ln69_21_fu_884_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln69_14_reg_1482 <= add_ln69_14_fu_988_p2;
        add_ln69_15_reg_1488 <= add_ln69_15_fu_997_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln69_1_reg_1149 <= add_ln69_1_fu_481_p2;
        add_ln69_reg_1141 <= add_ln69_fu_466_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln69_22_reg_1494 <= add_ln69_22_fu_1062_p2;
        add_ln69_23_reg_1500 <= add_ln69_23_fu_1067_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln69_24_reg_1506 <= add_ln69_24_fu_1072_p2;
        add_ln69_25_reg_1511 <= add_ln69_25_fu_1076_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln69_26_reg_1516 <= add_ln69_26_fu_1080_p2;
        add_ln69_27_reg_1521 <= add_ln69_27_fu_1084_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln69_28_reg_1526 <= add_ln69_28_fu_1088_p2;
        add_ln69_29_reg_1531 <= add_ln69_29_fu_1093_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln69_2_reg_1187 <= add_ln69_2_fu_496_p2;
        add_ln69_3_reg_1195 <= add_ln69_3_fu_511_p2;
        d_i_0_load_1_reg_1200 <= d_i_0_q1;
        d_i_1_load_1_reg_1206 <= d_i_1_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        add_ln69_30_reg_1536 <= add_ln69_30_fu_1098_p2;
        add_ln69_31_reg_1541 <= add_ln69_31_fu_1103_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        reg_442 <= d_i_0_q0;
        reg_446 <= d_i_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)))) begin
        reg_450 <= d_i_2_q0;
        reg_454 <= d_i_3_q0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_0_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_0_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_0_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_0_address0 = 64'd0;
    end else begin
        d_i_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_0_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_0_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_0_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_0_address1 = 64'd1;
    end else begin
        d_i_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        d_i_0_ce0 = 1'b1;
    end else begin
        d_i_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        d_i_0_ce1 = 1'b1;
    end else begin
        d_i_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_1_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_1_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        d_i_1_address0 = 64'd0;
    end else begin
        d_i_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_1_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_1_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_1_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_1_address1 = 64'd1;
    end else begin
        d_i_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        d_i_1_ce0 = 1'b1;
    end else begin
        d_i_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        d_i_1_ce1 = 1'b1;
    end else begin
        d_i_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_2_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_2_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_2_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_2_address0 = 64'd0;
    end else begin
        d_i_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_2_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_2_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_2_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_2_address1 = 64'd1;
    end else begin
        d_i_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        d_i_2_ce0 = 1'b1;
    end else begin
        d_i_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        d_i_2_ce1 = 1'b1;
    end else begin
        d_i_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_3_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_3_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        d_i_3_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        d_i_3_address0 = 64'd0;
    end else begin
        d_i_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        d_i_3_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        d_i_3_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        d_i_3_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        d_i_3_address1 = 64'd1;
    end else begin
        d_i_3_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        d_i_3_ce0 = 1'b1;
    end else begin
        d_i_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        d_i_3_ce1 = 1'b1;
    end else begin
        d_i_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        d_o_0_blk_n = d_o_0_full_n;
    end else begin
        d_o_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            d_o_0_din = add_ln69_30_reg_1536;
        end else if ((1'b1 == ap_CS_fsm_state17)) begin
            d_o_0_din = add_ln69_28_reg_1526;
        end else if ((1'b1 == ap_CS_fsm_state16)) begin
            d_o_0_din = add_ln69_26_reg_1516;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            d_o_0_din = add_ln69_24_reg_1506;
        end else if ((1'b1 == ap_CS_fsm_state14)) begin
            d_o_0_din = add_ln69_22_reg_1494;
        end else if ((1'b1 == ap_CS_fsm_state13)) begin
            d_o_0_din = add_ln69_20_reg_1460;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            d_o_0_din = add_ln69_18_reg_1378;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            d_o_0_din = add_ln69_16_reg_1300;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            d_o_0_din = add_ln69_14_reg_1482;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            d_o_0_din = add_ln69_12_reg_1450;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            d_o_0_din = add_ln69_10_reg_1368;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            d_o_0_din = add_ln69_8_reg_1280;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            d_o_0_din = add_ln69_6_fu_612_p2;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            d_o_0_din = add_ln69_4_fu_526_p2;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            d_o_0_din = add_ln69_2_fu_496_p2;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            d_o_0_din = add_ln69_fu_466_p2;
        end else begin
            d_o_0_din = 'bx;
        end
    end else begin
        d_o_0_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state16)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state12)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        d_o_0_write = 1'b1;
    end else begin
        d_o_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        d_o_1_blk_n = d_o_1_full_n;
    end else begin
        d_o_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0))) begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            d_o_1_din = add_ln69_31_reg_1541;
        end else if ((1'b1 == ap_CS_fsm_state17)) begin
            d_o_1_din = add_ln69_29_reg_1531;
        end else if ((1'b1 == ap_CS_fsm_state16)) begin
            d_o_1_din = add_ln69_27_reg_1521;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            d_o_1_din = add_ln69_25_reg_1511;
        end else if ((1'b1 == ap_CS_fsm_state14)) begin
            d_o_1_din = add_ln69_23_reg_1500;
        end else if ((1'b1 == ap_CS_fsm_state13)) begin
            d_o_1_din = add_ln69_21_reg_1466;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            d_o_1_din = add_ln69_19_reg_1384;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            d_o_1_din = add_ln69_17_reg_1306;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            d_o_1_din = add_ln69_15_reg_1488;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            d_o_1_din = add_ln69_13_reg_1455;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            d_o_1_din = add_ln69_11_reg_1373;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            d_o_1_din = add_ln69_9_reg_1285;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            d_o_1_din = add_ln69_7_fu_626_p2;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            d_o_1_din = add_ln69_5_fu_540_p2;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            d_o_1_din = add_ln69_3_fu_511_p2;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            d_o_1_din = add_ln69_1_fu_481_p2;
        end else begin
            d_o_1_din = 'bx;
        end
    end else begin
        d_o_1_din = 'bx;
    end
end

always @ (*) begin
    if (((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state16)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state12)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5)) | (~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4)))) begin
        d_o_1_write = 1'b1;
    end else begin
        d_o_1_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if ((~((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_10_fu_782_p2 = ($signed(sext_ln67_15_fu_779_p1) + $signed(sext_ln69_2_fu_758_p1));

assign add_ln67_12_fu_804_p2 = ($signed(acc_3) + $signed(sext_ln67_3_fu_754_p1));

assign add_ln67_13_fu_744_p2 = ($signed(sext_ln69_11_fu_660_p1) + $signed(sext_ln67_17_fu_740_p1));

assign add_ln67_14_fu_812_p2 = ($signed(sext_ln67_18_fu_809_p1) + $signed(sext_ln69_3_fu_762_p1));

assign add_ln67_16_fu_898_p2 = ($signed(acc_4) + $signed(sext_ln67_4_fu_854_p1));

assign add_ln67_17_fu_838_p2 = ($signed(sext_ln69_12_fu_766_p1) + $signed(sext_ln67_20_fu_834_p1));

assign add_ln67_18_fu_906_p2 = ($signed(sext_ln67_21_fu_903_p1) + $signed(sext_ln69_4_fu_860_p1));

assign add_ln67_1_fu_580_p2 = ($signed(sext_ln69_8_fu_556_p1) + $signed(sext_ln67_8_fu_576_p1));

assign add_ln67_20_fu_928_p2 = ($signed(acc_5) + $signed(sext_ln67_5_fu_857_p1));

assign add_ln67_21_fu_848_p2 = ($signed(sext_ln69_13_fu_770_p1) + $signed(sext_ln67_23_fu_844_p1));

assign add_ln67_22_fu_936_p2 = ($signed(sext_ln67_24_fu_933_p1) + $signed(sext_ln69_5_fu_869_p1));

assign add_ln67_24_fu_1002_p2 = ($signed(acc_6) + $signed(sext_ln67_6_fu_978_p1));

assign add_ln67_25_fu_962_p2 = ($signed(sext_ln69_14_fu_890_p1) + $signed(sext_ln67_26_fu_958_p1));

assign add_ln67_26_fu_1010_p2 = ($signed(sext_ln67_27_fu_1007_p1) + $signed(sext_ln69_6_fu_984_p1));

assign add_ln67_28_fu_1032_p2 = ($signed(acc_7) + $signed(sext_ln67_7_fu_981_p1));

assign add_ln67_29_fu_972_p2 = ($signed(sext_ln69_15_fu_894_p1) + $signed(sext_ln67_29_fu_968_p1));

assign add_ln67_2_fu_678_p2 = ($signed(sext_ln67_9_fu_675_p1) + $signed(sext_ln69_fu_632_p1));

assign add_ln67_30_fu_1040_p2 = ($signed(sext_ln67_30_fu_1037_p1) + $signed(sext_ln69_7_fu_993_p1));

assign add_ln67_4_fu_700_p2 = ($signed(acc_1) + $signed(sext_ln67_1_fu_600_p1));

assign add_ln67_5_fu_590_p2 = ($signed(sext_ln69_9_fu_566_p1) + $signed(sext_ln67_11_fu_586_p1));

assign add_ln67_6_fu_708_p2 = ($signed(sext_ln67_12_fu_705_p1) + $signed(sext_ln69_1_fu_636_p1));

assign add_ln67_8_fu_774_p2 = ($signed(acc_2) + $signed(sext_ln67_2_fu_750_p1));

assign add_ln67_9_fu_734_p2 = ($signed(sext_ln69_10_fu_650_p1) + $signed(sext_ln67_14_fu_730_p1));

assign add_ln67_fu_670_p2 = ($signed(acc_0) + $signed(sext_ln67_fu_596_p1));

assign add_ln69_10_fu_640_p2 = ($signed(reg_432) + $signed(add_ln69_2_reg_1187));

assign add_ln69_11_fu_645_p2 = ($signed(reg_437) + $signed(add_ln69_3_reg_1195));

assign add_ln69_12_fu_864_p2 = ($signed(reg_442) + $signed(add_ln69_4_reg_1255));

assign add_ln69_13_fu_873_p2 = ($signed(reg_446) + $signed(add_ln69_5_reg_1263));

assign add_ln69_14_fu_988_p2 = ($signed(reg_450) + $signed(add_ln69_6_reg_1355));

assign add_ln69_15_fu_997_p2 = ($signed(reg_454) + $signed(add_ln69_7_reg_1363));

assign add_ln69_16_fu_560_p2 = ($signed(reg_442) + $signed(add_ln69_8_fu_546_p2));

assign add_ln69_17_fu_570_p2 = ($signed(reg_446) + $signed(add_ln69_9_fu_551_p2));

assign add_ln69_18_fu_654_p2 = ($signed(reg_450) + $signed(add_ln69_10_fu_640_p2));

assign add_ln69_19_fu_664_p2 = ($signed(reg_454) + $signed(add_ln69_11_fu_645_p2));

assign add_ln69_1_fu_481_p2 = ($signed(reg_407) + $signed(trunc_ln67_1_fu_477_p1));

assign add_ln69_20_fu_878_p2 = ($signed(reg_402) + $signed(add_ln69_12_fu_864_p2));

assign add_ln69_21_fu_884_p2 = ($signed(reg_407) + $signed(add_ln69_13_fu_873_p2));

assign add_ln69_22_fu_1062_p2 = ($signed(reg_412) + $signed(add_ln69_14_reg_1482));

assign add_ln69_23_fu_1067_p2 = ($signed(reg_417) + $signed(add_ln69_15_reg_1488));

assign add_ln69_24_fu_1072_p2 = ($signed(d_i_0_load_6_reg_1322) + $signed(add_ln69_16_reg_1300));

assign add_ln69_25_fu_1076_p2 = ($signed(d_i_1_load_6_reg_1332) + $signed(add_ln69_17_reg_1306));

assign add_ln69_26_fu_1080_p2 = ($signed(d_i_2_load_6_reg_1400) + $signed(add_ln69_18_reg_1378));

assign add_ln69_27_fu_1084_p2 = ($signed(d_i_3_load_6_reg_1410) + $signed(add_ln69_19_reg_1384));

assign add_ln69_28_fu_1088_p2 = ($signed(reg_422) + $signed(add_ln69_20_reg_1460));

assign add_ln69_29_fu_1093_p2 = ($signed(reg_427) + $signed(add_ln69_21_reg_1466));

assign add_ln69_2_fu_496_p2 = ($signed(reg_412) + $signed(trunc_ln67_2_fu_492_p1));

assign add_ln69_30_fu_1098_p2 = ($signed(reg_432) + $signed(add_ln69_22_reg_1494));

assign add_ln69_31_fu_1103_p2 = ($signed(reg_437) + $signed(add_ln69_23_reg_1500));

assign add_ln69_3_fu_511_p2 = ($signed(reg_417) + $signed(trunc_ln67_3_fu_507_p1));

assign add_ln69_4_fu_526_p2 = ($signed(d_i_0_load_1_reg_1200) + $signed(trunc_ln67_4_fu_522_p1));

assign add_ln69_5_fu_540_p2 = ($signed(d_i_1_load_1_reg_1206) + $signed(trunc_ln67_5_fu_536_p1));

assign add_ln69_6_fu_612_p2 = ($signed(d_i_2_load_1_reg_1268) + $signed(trunc_ln67_6_fu_608_p1));

assign add_ln69_7_fu_626_p2 = ($signed(d_i_3_load_1_reg_1274) + $signed(trunc_ln67_7_fu_622_p1));

assign add_ln69_8_fu_546_p2 = ($signed(reg_422) + $signed(add_ln69_reg_1141));

assign add_ln69_9_fu_551_p2 = ($signed(reg_427) + $signed(add_ln69_1_reg_1149));

assign add_ln69_fu_466_p2 = ($signed(reg_402) + $signed(trunc_ln67_fu_462_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state11 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state12 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state13 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state14 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state15 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state16 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state17 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state18 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state8 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state9 = ((d_o_1_full_n == 1'b0) | (d_o_0_full_n == 1'b0));
end

assign sext_ln67_10_fu_684_p1 = $signed(add_ln67_2_fu_678_p2);

assign sext_ln67_11_fu_586_p0 = d_i_1_q1;

assign sext_ln67_11_fu_586_p1 = sext_ln67_11_fu_586_p0;

assign sext_ln67_12_fu_705_p1 = $signed(add_ln67_5_reg_1337);

assign sext_ln67_13_fu_714_p1 = $signed(add_ln67_6_fu_708_p2);

assign sext_ln67_14_fu_730_p0 = d_i_2_q1;

assign sext_ln67_14_fu_730_p1 = sext_ln67_14_fu_730_p0;

assign sext_ln67_15_fu_779_p1 = $signed(add_ln67_9_reg_1405);

assign sext_ln67_16_fu_788_p1 = $signed(add_ln67_10_fu_782_p2);

assign sext_ln67_17_fu_740_p0 = d_i_3_q1;

assign sext_ln67_17_fu_740_p1 = sext_ln67_17_fu_740_p0;

assign sext_ln67_18_fu_809_p1 = $signed(add_ln67_13_reg_1415);

assign sext_ln67_19_fu_818_p1 = $signed(add_ln67_14_fu_812_p2);

assign sext_ln67_1_fu_600_p1 = reg_407;

assign sext_ln67_20_fu_834_p0 = d_i_0_q1;

assign sext_ln67_20_fu_834_p1 = sext_ln67_20_fu_834_p0;

assign sext_ln67_21_fu_903_p1 = $signed(add_ln67_17_reg_1430);

assign sext_ln67_22_fu_912_p1 = $signed(add_ln67_18_fu_906_p2);

assign sext_ln67_23_fu_844_p0 = d_i_1_q1;

assign sext_ln67_23_fu_844_p1 = sext_ln67_23_fu_844_p0;

assign sext_ln67_24_fu_933_p1 = $signed(add_ln67_21_reg_1435);

assign sext_ln67_25_fu_942_p1 = $signed(add_ln67_22_fu_936_p2);

assign sext_ln67_26_fu_958_p0 = d_i_2_q1;

assign sext_ln67_26_fu_958_p1 = sext_ln67_26_fu_958_p0;

assign sext_ln67_27_fu_1007_p1 = $signed(add_ln67_25_reg_1472);

assign sext_ln67_28_fu_1016_p1 = $signed(add_ln67_26_fu_1010_p2);

assign sext_ln67_29_fu_968_p0 = d_i_3_q1;

assign sext_ln67_29_fu_968_p1 = sext_ln67_29_fu_968_p0;

assign sext_ln67_2_fu_750_p1 = reg_412;

assign sext_ln67_30_fu_1037_p1 = $signed(add_ln67_29_reg_1477);

assign sext_ln67_31_fu_1046_p1 = $signed(add_ln67_30_fu_1040_p2);

assign sext_ln67_3_fu_754_p1 = reg_417;

assign sext_ln67_4_fu_854_p1 = d_i_0_load_1_reg_1200;

assign sext_ln67_5_fu_857_p1 = d_i_1_load_1_reg_1206;

assign sext_ln67_6_fu_978_p1 = d_i_2_load_1_reg_1268;

assign sext_ln67_7_fu_981_p1 = d_i_3_load_1_reg_1274;

assign sext_ln67_8_fu_576_p0 = d_i_0_q1;

assign sext_ln67_8_fu_576_p1 = sext_ln67_8_fu_576_p0;

assign sext_ln67_9_fu_675_p1 = $signed(add_ln67_1_reg_1327);

assign sext_ln67_fu_596_p1 = reg_402;

assign sext_ln69_10_fu_650_p1 = reg_450;

assign sext_ln69_11_fu_660_p1 = reg_454;

assign sext_ln69_12_fu_766_p1 = reg_402;

assign sext_ln69_13_fu_770_p1 = reg_407;

assign sext_ln69_14_fu_890_p1 = reg_412;

assign sext_ln69_15_fu_894_p1 = reg_417;

assign sext_ln69_1_fu_636_p1 = reg_427;

assign sext_ln69_2_fu_758_p1 = reg_432;

assign sext_ln69_3_fu_762_p1 = reg_437;

assign sext_ln69_4_fu_860_p1 = reg_442;

assign sext_ln69_5_fu_869_p1 = reg_446;

assign sext_ln69_6_fu_984_p1 = reg_450;

assign sext_ln69_7_fu_993_p1 = reg_454;

assign sext_ln69_8_fu_556_p1 = reg_442;

assign sext_ln69_9_fu_566_p1 = reg_446;

assign sext_ln69_fu_632_p1 = reg_422;

assign temp_1_fu_718_p2 = ($signed(sext_ln67_13_fu_714_p1) + $signed(add_ln67_4_fu_700_p2));

assign temp_2_fu_792_p2 = ($signed(sext_ln67_16_fu_788_p1) + $signed(add_ln67_8_fu_774_p2));

assign temp_3_fu_822_p2 = ($signed(sext_ln67_19_fu_818_p1) + $signed(add_ln67_12_fu_804_p2));

assign temp_4_fu_916_p2 = ($signed(sext_ln67_22_fu_912_p1) + $signed(add_ln67_16_fu_898_p2));

assign temp_5_fu_946_p2 = ($signed(sext_ln67_25_fu_942_p1) + $signed(add_ln67_20_fu_928_p2));

assign temp_6_fu_1020_p2 = ($signed(sext_ln67_28_fu_1016_p1) + $signed(add_ln67_24_fu_1002_p2));

assign temp_7_fu_1050_p2 = ($signed(sext_ln67_31_fu_1046_p1) + $signed(add_ln67_28_fu_1032_p2));

assign temp_fu_688_p2 = ($signed(sext_ln67_10_fu_684_p1) + $signed(add_ln67_fu_670_p2));

assign trunc_ln67_1_fu_477_p1 = acc_1[15:0];

assign trunc_ln67_2_fu_492_p1 = acc_2[15:0];

assign trunc_ln67_3_fu_507_p1 = acc_3[15:0];

assign trunc_ln67_4_fu_522_p1 = acc_4[15:0];

assign trunc_ln67_5_fu_536_p1 = acc_5[15:0];

assign trunc_ln67_6_fu_608_p1 = acc_6[15:0];

assign trunc_ln67_7_fu_622_p1 = acc_7[15:0];

assign trunc_ln67_fu_462_p1 = acc_0[15:0];

endmodule //array_io
